### ISSUE TITLE
JS ERROR SyntaxError: Importing binding name 'Input' is not found.

### ISSUE THREAD

**Issue by jfrazier007** [NepipenkoIgor/ng2-mask#10]
Has anyone experienced the following error when using Ng2MaskModule in an Angular 2 /Nativescript project?

When I add the module dependency into the app.module.ts file, I get the following error.
JS ERROR SyntaxError: Importing binding name 'Input' is not found.

Thanks!

**Comment by victorschinaider** [comment]
Can you provide some code?
