### ISSUE TITLE
More digits at FormControl that was typed

### ISSUE THREAD

**Issue by victorschinaider** [NepipenkoIgor/ng2-mask#11]
**TEMPLATE**

```typescript
 <input placeholder="CEP" [formControl]="form.get('dadosEndereco.endereco.cep')" mask="99999-999">
```

When i type more digits that was defined in mask, strange behavior happens, the last typed digit in definied in FormControl value, so the value has one more digit.

![image](https://cloud.githubusercontent.com/assets/16581931/25231161/2daef888-25ad-11e7-9c23-b12cea412b41.png)

**Comment by NepipenkoIgor** [comment]
@victorschinaider Thanks for issue, we will update our module. If you want you could help with it

**Comment by victorschinaider** [comment]
@NepipenkoIgor , thanks! I'll study the code too...

**Comment by victorschinaider** [comment]
@NepipenkoIgor, i fixed the bug in the forked repo. I'll create a merge reques soon. I updated to the lastest Angular/cli too.

Could i propose a change in layout of examples? Instead using bootstrap, maybe the Material2, what do you think?

**Comment by NepipenkoIgor** [comment]
@victorschinaider i think it will be awesome
