### ISSUE TITLE
Import Problem

### ISSUE THREAD

**Issue by deepakzoto** [NepipenkoIgor/ng2-mask#14]
I am getting this error  while executing 'ng serve': 

ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 10:22 in the original .ts file), resolving symbol Ng2MaskModule in D:/GitWork/web-ui/node_modules/ng2-mask/build/ng2-mask.module.js, resolving symbol AppModule in D:/GitWork/web-ui/src/app/app.module.ts, resolving symbol AppModule in D:/GitWork/web-ui/src/app/app.module.ts

This is my package.json:
`  "dependencies": {
  "@angular/animations": "^4.0.2",
    "@angular/common": "^4.0.2",
    "@angular/compiler": "^4.0.2",
    "@angular/core": "^4.0.2",
    "@angular/forms": "^4.0.2",
    "@angular/http": "^4.0.2",
    "@angular/material": "^2.0.0-beta.3",
    "@angular/platform-browser": "^4.0.2",
    "@angular/platform-browser-dynamic": "^4.0.2",
    "@angular/platform-server": "^4.0.2",
    "@angular/router": "^4.0.2",
    "@angular/upgrade": "^4.0.2",
    "angular-utf8-base64": "0.0.5",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "crypto-js": "^3.1.9-1",
    "hammerjs": "^2.0.8",
    "jquery": "^3.2.1",
    "lodash": "^4.17.4",
    "material": "^0.1.1",
    "md2": "0.0.19",
    "ng2-device-detector": "^0.1.0",
    "ng2-mask": "^0.5.2",
    "ntypescript": "^1.201609302242.1",
    "reflect-metadata": "^0.1.10",
    "rxjs": "^5.1.0",
    "systemjs": "^0.20.12",
    "underscore": "^1.8.3",
    "zone.js": "^0.8.4"
  },
`

**Comment by NepipenkoIgor** [comment]
@deepakzoto Hi, you used old version 0.5.2 (it was corrupted version) . Please use last release. Now current version is 1.0.1
