### ISSUE TITLE
input trying to load data

### ISSUE THREAD

**Issue by Sevensnake** [NepipenkoIgor/ng2-mask#20]
when using a click function to pass json object to input text box nothing shows. It works if I type it in but not loading.

ERROR Error: Uncaught (in promise): TypeError: inputValue.split is not a function
TypeError: inputValue.split is not a function
    at MaskDirective._applyMask (mask.directive.js:94)
    at MaskDirective.writeValue (mask.directive.js:72)

**Comment by NepipenkoIgor** [comment]
@Sevensnake Сould you provide some code snippet ?
