### ISSUE TITLE
Errors while compiling

### ISSUE THREAD

**Issue by ebosantos** [NepipenkoIgor/ng2-mask#4]
ERROR in [default] .../node_modules/ng2-mask/src/app/ng2-mask/mask.directive.ts:70:45 
Property 'includes' does not exist on type 'string[]'.

ERROR in [default] .../node_modules/ng2-mask/src/app/ng2-mask/mask.directive.ts:81:37 
Property 'includes' does not exist on type 'string[]'.

Changed to indexOf > -1 and it's working fine.

Tks

**Comment by stevermeister** [comment]
@ebosantos thanks for feedback!
we are still trying to figure out what structure to take to have DIST and SRC workable.
will produce fix with next update. and  sorry for unstable version

**Comment by stevermeister** [comment]
@ebosantos 
fixed, please check
