### ISSUE TITLE
ERROR in Ng2MaskModule is not an NgModule

### ISSUE THREAD

**Issue by daviddiefenderfer** [NepipenkoIgor/ng2-mask#7]
Has anyone ran into this error? I did the install and 
`import { Ng2MaskModule } from 'ng2-mask';`
then added it to my imports in the `app.module` and get
`ERROR in Ng2MaskModule is not an NgModule` when running ng serve

Curious if this is something anyone has run into before I start digging around

**Comment by NepipenkoIgor** [comment]
Thanks you very much  for you  feedback. We found out that new version of typescript had broken the library. Now it should be fix, please check it.

**Comment by NepipenkoIgor** [comment]
Thanks you very much for you feedback. We found out that new version of typescript had broken the library. Now it should be fix, please check it.

**Comment by NepipenkoIgor** [comment]
Thanks you very much for you feedback. We found out that new version of typescript had broken the library. Now it should be fix, please check it.

**Comment by daviddiefenderfer** [comment]
Awesome this fixed it, thanks for the quick resolution
