### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by henriquecustodia** [NepipenkoIgor/ng2-mask#9]
I'm very interest to use this module but I need a documentation to understand at least the mask pattern. 

This module is alive yet? 

I can contribute with if it help.

Thanks.

**Comment by NepipenkoIgor** [comment]
@henriquecustodia We have only demo 
https://nepipenkoigor.github.io/ng2-mask/

It will be perfect if you help with documentation and other things

**Comment by henriquecustodia** [comment]
Sure, I'll try help to improve the doc. 

Will you add unmask functionality yet? Has some issue about this?

**Comment by NepipenkoIgor** [comment]
unmask functionality - no . We can discuss and add new issues

**Comment by henriquecustodia** [comment]
Sure. 

The unmask functionality is just cleans the value goes to model, but the html field value continues masked. 
It's very useful to avoid use sanitizes functions out the directive.
